### ISSUE TITLE
Program crashes when viewing single m/z histograms.

### ISSUE THREAD

**Issue by melinkhuber** [djdt/spcal#18] opened 2024-05-29 10:14 UTC
**Affected version 1.2.4**

### Error description
I use the Nu non-targeted import for ICP-TOFMS data. I process data without quantification.
Initially, event recognition looks as usual. However, when I try to get the histogram view of a single m/z in the results tab, SpCal crashes. 

Error notification window opens:
Title: "Uncaught Exception.
Message: "cannot convert float NaN to integer".

Entire program shuts down after clicking OK.

### Hypothesis
- There are blanking event gaps in the data. When I exclude the gaps from the selected time region, everything is fine.
- In version 1.2.2. the exception is also thrown but SpCal does not crash. In this version, the single m/z plot is shown but the dashed "LOD" line is not shown. It appears that the error comes from calculating the LOD marker line.
- The error does not appear when using default thresholding settings, i.e., automatic, non-iterative and no window.
Settings for thresholding that cause the crash: Poisson, iterative, window = 1000.

Cheers!

**Comment by djdt** [comment] 2024-06-03 07:18
Hi,

I am guessing this is caused by NaNs getting into the histogram data. Can you send the sample file causing the crash?

Cheers

**Comment by djdt** [comment] 2024-06-18 06:04
Closed by #19.

**Closed by djdt** 2024-06-18 06:04 UTC
